# This workflow will install Python dependencies and then build NUSGet for all platforms

name: Tag Python application

on:
  push:
    tags:
      - "*"

permissions:
  contents: read

jobs:
  build-linux-x86_64:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
    - name: Install system deps for Nuitka
      run: |
        sudo apt update && \
        sudo apt install -y ccache patchelf
    - name: Set up Python 3.13
      uses: actions/setup-python@v6
      with:
        python-version: "3.13"
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Build Package
      run: make all
    - name: Prepare Package for Upload
      run: |
        mv NUSGet ~/NUSGet
        cd ~
        tar cvf NUSGet.tar NUSGet
    - name: Upload Package
      uses: actions/upload-artifact@v7
      with:
        path: ~/NUSGet.tar
        name: NUSGet-Linux-x86_64-bin

  build-macos-x86_64:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v6
      - name: Set up Python 3.13
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Build Package
        run: ARCH_FLAGS=--macos-target-arch=x86_64 make all
      - name: Import Signing Certificate
        env:
          APPLE_DEVELOPERID_CERT_BASE64: ${{ secrets.APPLE_DEVELOPERID_CERT_BASE64 }}
          APPLE_DEVELOPERID_PASSWORD: ${{ secrets.APPLE_DEVELOPERID_PASSWORD }}
        run: |
          set -euxo pipefail
          
          KEYCHAIN_PATH="$RUNNER_TEMP/codesign.keychain-db"

          echo -n "$APPLE_DEVELOPERID_CERT_BASE64" | base64 -d -o ./developerid-cert.p12
      
          security create-keychain -p "" "$KEYCHAIN_PATH"
          security set-keychain-settings -lut 21600 "$KEYCHAIN_PATH"
          security unlock-keychain -p "" "$KEYCHAIN_PATH"
          security list-keychains -d user -s "$KEYCHAIN_PATH"
          security default-keychain -d user -s "$KEYCHAIN_PATH"
      
          security import ./developerid-cert.p12 \
            -k "$KEYCHAIN_PATH" \
            -P "$APPLE_DEVELOPERID_PASSWORD" \
            -A -t cert -f pkcs12
      
          security set-key-partition-list \
            -S apple-tool:,apple: \
            -s -k "" "$KEYCHAIN_PATH"
      
          security find-identity -v -p codesigning "$KEYCHAIN_PATH"
      - name: Sign and Notarize Bundle
        env:
          APPLE_NOTARYTOOL_APPLEID: ${{ secrets.APPLE_NOTARYTOOL_APPLEID }}
          APPLE_NOTARYTOOL_PASSWORD: ${{ secrets.APPLE_NOTARYTOOL_PASSWORD }}
        run: |
          set -euxo pipefail
          
          codesign --force --deep --timestamp --options runtime \
            -s "Developer ID Application: Campbell Bagley (5GF7GKNTK4)" \
            NUSGet.app

          codesign --verify --deep --strict --verbose=2 NUSGet.app
          
          ditto -c -k --keepParent NUSGet.app NUSGet_notarize.zip
          
          xcrun notarytool submit NUSGet_notarize.zip \
            --apple-id $APPLE_NOTARYTOOL_APPLEID \
            --team-id "5GF7GKNTK4" \
            --password $APPLE_NOTARYTOOL_PASSWORD \
            --wait --progress
            
          xcrun stapler staple NUSGet.app
          rm NUSGet_notarize.zip
          mkdir NUSGet-signed
          mv NUSGet.app NUSGet-signed/
          ditto -c -k --keepParent NUSGet-signed NUSGet.zip
      - name: Upload Package
        uses: actions/upload-artifact@v7
        with:
          path: ~/NUSGet.zip
          name: NUSGet-macOS-x86_64-bin

  build-macos-arm64:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v6
      - name: Set up Python 3.12
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Build Package
        run: ARCH_FLAGS=--macos-target-arch=arm64 make all
      - name: Prepare Package for Upload
        run: |
          mv NUSGet.app ~/NUSGet.app
          cd ~
          tar cvf NUSGet.tar NUSGet.app
      - name: Upload Package
        uses: actions/upload-artifact@v7
        with:
          path: ~/NUSGet.tar
          name: NUSGet-macOS-arm64-bin

  build-windows-x86_64:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v6
    - name: Set up Python 3.13
      uses: actions/setup-python@v6
      with:
        python-version: "3.13"
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Build Standalone Package
      run: .\Build.ps1
    - name: Upload Unsigned Standalone Package
      id: upload-unsigned-standalone
      uses: actions/upload-artifact@v7
      with:
        path: D:\a\NUSGet\NUSGet\NUSGet.dist
        name: NUSGet-Windows-x86_64-bin
    - name: Sign Standalone Package (TESTING)
      uses: signpath/github-action-submit-signing-request@v2
      with:
        api-token: '${{ secrets.SIGNPATH_API_TOKEN }}'
        organization-id: 'c162cb9c-9ce8-4539-a7ed-08527a44249f'
        project-slug: 'NUSGet'
        signing-policy-slug: 'test-signing'
        github-artifact-id: '${{ steps.upload-unsigned-standalone.outputs.artifact-id }}'
        wait-for-completion: true
        output-artifact-directory: '.\signed-package'
    - name: Upload Signed Standalone Package
      uses: actions/upload-artifact@v7
      with:
        path: .\signed-package
        name: NUSGet-Windows-x86_64-signed-bin

  build-windows-onefile-x86_64:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v6
    - name: Set up Python 3.13
      uses: actions/setup-python@v6
      with:
        python-version: "3.13"
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Build Onefile Package
      run: .\Build.ps1 build-onefile
    - name: Upload Unsigned Onefile Package
      id: upload-unsigned-onefile
      uses: actions/upload-artifact@v7
      with:
        path: D:\a\NUSGet\NUSGet\NUSGet.exe
        name: NUSGet-Windows-onefile-x86_64-bin
    - name: Sign Onefile Package (TESTING)
      uses: signpath/github-action-submit-signing-request@v2
      with:
        api-token: '${{ secrets.SIGNPATH_API_TOKEN }}'
        organization-id: 'c162cb9c-9ce8-4539-a7ed-08527a44249f'
        project-slug: 'NUSGet'
        signing-policy-slug: 'test-signing'
        github-artifact-id: '${{ steps.upload-unsigned-onefile.outputs.artifact-id }}'
        wait-for-completion: true
        output-artifact-directory: '.\signed-package'
    - name: Upload Signed Onefile Package
      uses: actions/upload-artifact@v7
      with:
        path: .\signed-package\NUSGet.exe
        name: NUSGet-Windows-onefile-x86_64-signed-bin
        
